### ISSUE TITLE
Naive Arbitrage Strategy Implementation: Arbitrage Opportunity Execution

### ISSUE THREAD

**Issue by dowlandaiello** [timewave-computer/auction-arbitrage-bot#2]
The auction arbitrage bot should be configurable via flags and environment variables to execute trades on the user's behalf in addition to identifying arbitrage opportunities. In addition, users should be able to simulate execution of trades, with live feedback provided via an HTTP API. Example routes may include:

* `GET /trades` - Returns a JSON array of completed trades:

```json
[
  {
    "profit": 1234,
    "profit_denom": "ibc/xyz",
    "timestamp_completed": 1234,
    "route": [
      {
        {
          "osmosis": {
            // See pool_file format in README.md
          },
          "neutron_astroport": {
            // See README.md
          }
        }
      }
    ]
  }
]
```

* `GET /routes` - Returns a JSON array of known routes

```json
[
  [
    "osmosis": {
      // See README.md
    },
    "neutron_astroport": {
      // See README.md
    }
  ]
]
```

* `GET /status` - Returns a JSON object representing current stats for the bot

```json
{
  "completed_trades": 1234,
  "profit": 1234,
  "profit_denom": "ibc/xyz"
}
```

**Comment by stiiifff** [comment]
@dowlandaiello can this be closed ? I don't see any open PR linked to it ..
