### ISSUE TITLE
Refine Arbitrage Bot to Meet Target Profit Milestone Criteria

### ISSUE THREAD

**Issue by dowlandaiello** [timewave-computer/auction-arbitrage-bot#7]
After achieving prototyped arbitrage trade execution, the arbitrage bot should be refined and optimized in order to exceed the existing market maker contract's profit over a 7 day window. This will include technical optimizations (e.g., caching, laziness where possible), route discovery algorithm refinement, and other possible optimizations.

*Note: Need clarification on the margin by which the arb bot must exceed the existing contract's profit.*

**Comment by stiiifff** [comment]
@dowlandaiello any update on this one ?
